### ISSUE TITLE
NextGen ActionScript extension exited with error code 1

### ISSUE THREAD

**Issue by JohnSword** [BowlerHatLLC/vscode-nextgenas#7]
getting this error even though I'm using:

java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

**Comment by joshtynjala** [comment]
Which operating system are you running? And which version of Visual Studio Code? Thanks!

**Comment by JohnSword** [comment]
I'm running Windows 7 Pro and VSC 1.6.1

**Comment by joshtynjala** [comment]
Thank you. Someone else just reported the same error on macOS, so I'm thinking it might be an issue with a recent VSCode update rather than platform-specific. I am currently on vacation with family, but I will take a look on Tuesday when I'm back at work. In the meantime, you could possibly try rolling back to an older build of VSCode.

**Comment by joshtynjala** [comment]
So, just to confirm, if you open up the command line and run `java -version`, you see 1.8? The reason I ask is that this error was coming up for the other person because the VSCode extension was finding an older version of Java instead of 1.8. They had multiple versions of Java installed, and 1.8 was showing up in their system settings, but their command line PATH was still defaulting to 1.7.

**Comment by joshtynjala** [comment]
Okay, so that's explains it. The extension checks JAVA_HOME before PATH, but it doesn't currently know how to read the version of Java. It uses the first version of Java it finds, so it's finding Java 1.7.

If you want to run the current version of the extension, you'll either need to clear JAVA_HOME or update it to point to Java 1.8 instead of 1.7.

In the next build, I'm going to try to find a way for the extension to check the version of Java before choosing it. If JAVA_HOME is too old, it will move on to PATH and keep trying to find a different version.

Sorry for the trouble, but thanks for the help tracking it down!

**Comment by JohnSword** [comment]
ok, I believe I use that version of Java (1.7/x86) in the JAVA_HOME because of Flash Builder. I remember the compiler had problems working with the most recent 64 bit versions of Java. But I'll change it and try it out to see if it works. Thanks Josh.

**Comment by JohnSword** [comment]
I was trying to debug a simple script, selected the nextgen option in the debugger configurations but I'm getting the following error: Attribute 'outDir' does not exist... (followed by the path to the project)

**Comment by joshtynjala** [comment]
It sounds like your bin/js-debug directory may not exist. Make sure that you create a tasks.json to build the project first:

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-tasks.json-to-compile-an-ActionScript-project

If you want it to build automatically before debugging, you can set the preLaunchTask in your launch.json to "asconfigc". Detailed instructions for the preLaunchTask are included in the pages about debugging that are on the wiki.

**Comment by JohnSword** [comment]
followed the instruction on that link, ctr+shift+b gives the following output in the console tab: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joshtynjala** [comment]
Can you share what your tasks.json looks like?

**Comment by JohnSword** [comment]
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		// "--flexHome=C:\\Development\\Apache Flex"
	],
	"showOutput": "always"
}

**Comment by joshtynjala** [comment]
And you tried uncommenting the line where the --flexHome argument is specified?

**Comment by JohnSword** [comment]
yes

**Comment by joshtynjala** [comment]
Can you try setting --flexHome to a path that does not contain spaces?

**Comment by JohnSword** [comment]
you mean changing the "Apache Flex" folder name? I tried, the system doesn't let me.

**Comment by JohnSword** [comment]
ok tried this:
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		"--flexHome=C:\\Development\\flex"
	],
	"showOutput": "always"
}

still not working

**Comment by JohnSword** [comment]
I did the "npm install -g asconfigc" thing but I cannot call asconfigc from the command line. Could that be the problem?

**Comment by joshtynjala** [comment]
Hmmm... yes, it does seem strange that asconfigc wouldn't work from the command line when installed globally.

**Comment by JohnSword** [comment]
nevermind, asconfigc is indeed working from the command line.

**Comment by JohnSword** [comment]
this is getting weirder... if I run asconfigc from the command line inside the project directory I get: 
SDK not found. Set FLEX_HOME, add to PATH, or use --flexHome option.

even though I've set the FLEX_HOME environment value.

if I do: asconfigc --flexHome C:\Development\flex
then I get that error:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joshtynjala** [comment]
I'm suspecting that Java is installed somewhere in "C:\Program Files\" on your computer, and I just remembered having a similar issue with another Node.js project in the past. Node has a few different ways to run another executable, and some of them did not work for me on Windows if there were spaces in the executable path.

I just opened BowlerHatLLC/asconfigc#5 to track this issue (since it's in asconfigc and not the VSCode extension). I'll try to run an older version of Windows in a VM to see if I can reproduce (I tested on Windows 10, and Java ends up somewhere in C:\ProgramData instead).

**Comment by JohnSword** [comment]
indeed, in fact I have Java installations all over the place. both in "C:\Program Files\Java" and "C:\Program Files (x86)"

**Comment by joshtynjala** [comment]
If you update to asconfigc 0.3.0, the issue with spaces in the paths is now fixed.

**Comment by mikhailkuts** [comment]
"NextGen ActionScript extension exited with error code 1" error still happens when I start VSC.
Win 10 64bit
VS Code 1.6.1
Java 8u111 (64bit) installed to C:\jdk8u111

**Comment by joshtynjala** [comment]
@mikhailkuts It's likely that the upcoming 0.2.0 will fix your issue or give you a better clue about what's wrong. I've built in better detection of certain things, but they have not been released yet.
