### ISSUE TITLE
False problem reported: 'js:valuesImpl' tag (or tag before this tag) is unclosed or tag not allowed here.

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#79]
There is problem reported but there is no problem.
How to reproduce: Using latest VSCode and latest extension (v0.4.2), create sample app with this code:
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:js="library://ns.apache.org/flexjs/basic">
	<js:initialView>
		<js:View>
			<js:Label text="Hello World" x="100" y="100"/>
		</js:View>
	</js:initialView>
	<js:valuesImpl>
		<js:SimpleCSSValuesImpl />
	</js:valuesImpl>
</js:Application>
```

1. after </js:initialView> press ENTER create new line, and write letter or two to get auto completion and click any of the auto complete suggestions.
2. do same in next new line. 
3. problem is reported, which is ok, like: 'This text is unexpected. It will be ignored.'
4. delete created lines (to get original sample code only), two problems appear:
message: 'This text is unexpected. It will be ignored.'
at: '8,19'
message: ''js:valuesImpl' tag (or tag before this tag) is unclosed or tag not allowed here.'
at: '11,2'

Workaround: Restart VSCode, problem is gone.

Comment: There should not be any problems. It looks something is not "refreshed" after deleting new lines. Could be related to https://github.com/BowlerHatLLC/vscode-nextgenas/issues/46#issuecomment-268132244

**Comment by joshtynjala** [comment]
I'm not able to reproduce this issue with version 0.4.2 of the extension. When I delete the extra lines, the errors go away. I tested with both FlexJS 0.7.0 and 0.8 nightly.

This sounds a bit like an old issue that I fixed in 0.3.1, where certain errors were not cleared out after they were fixed.

Have you ever installed the extension manually from a VSIX file? In some of my test environments, I've tried updating an extension from the VSCode Marketplace after I had an older VSIX version installed. It would appear in VSCode that the newer version was installed, but I would see behavior from an older version instead (old bugs and things). Then, when I uninstalled the extension, the older version from the VSIX file would show up in the Extensions list after restarting. I had to uninstall twice and then reinstall. I wouldn't expect that you would install the extension a VSIX file, but since I upload them in releases here on Github, I guess it's possible. If you have, try uninstalling (as many times as it takes, if the extension keeps showing up again).

**Comment by neminovno** [comment]
Could be that the extension was once installed manually, but anyway, after uninstalling, restart VSCode, installing again, once I got the same issue again. Still not sure how. While testing I noticed this line:
	xmlns:js="library://ns.apache.org/flexjs/basi **xmlns:ns1="com.adobe.tvsdk.mediacore.*"c**">
It looks like, while adding new namespace, existing namespace string is cut by minus one character. Maybe this is another issue. To get this issue just add some non "js" namespace component. For example: press "<", after auto complete dropdown appears, select first suggestion. In my case it was ABRControlParameters.

**Comment by neminovno** [comment]
Does the extension parse MXML tags or VSCode or?

**Comment by joshtynjala** [comment]
MXML is parsed and checked for errors by the compiler in the FlexJS SDK.

**Comment by joshtynjala** [comment]
If you can successfully build the same project, and the compiler output doesn't include an error either, then it's a compiler bug. If there is an error, then the extension has a bug and I need to figure out where the error is exposed.

**Comment by neminovno** [comment]
Ok. What is controlling when red marks (for problem code) appear?
Sometimes the issue disappears when close/open file, but always when VSCode is restarted.

**Comment by joshtynjala** [comment]
The extension tells VSCode which errors to underline. If an error won't go away, then it may be that the extension is failing to clear awayold errors. It's also possible that the compiler has a bug which causes it to get into a bad state.

**Comment by neminovno** [comment]
I think you are on good trail of it. It looks like last error is misreported again as error.

**Comment by neminovno** [comment]
Here is gif with example when problem appears:
![codenexgenas_mxml_bug_aa3](https://cloud.githubusercontent.com/assets/1468887/25669105/e3ce0958-3028-11e7-9d5d-1e42a2df0f3b.gif)

**Comment by joshtynjala** [comment]
Unfortunately, I'm still not able to reproduce either of the issues you reported in this thread.

**Comment by joshtynjala** [comment]
I randomly gave it a try on Windows today, and I could reproduce both issues. For some reason, they will not reproduce on macOS, though.

**Comment by joshtynjala** [comment]
So it turns out that the way that I was storing files in memory was changing all line endings to \n, even if the file's line endings where \r\n. This led to some things getting out of sync, and that caused both of these issues.

I will release version 0.4.3 next week with the fix.
